export type Card={id:string;name:string;number:string;set:string;rarity:string;pokemon:number;value:number;owned:number;language:string;condition:string;grade:string;year:number};
export const cards:Card[]=[
{id:'charizard',name:'Charizard ex',number:'199',set:'Scarlet & Violet 151',rarity:'Special Illustration Rare',pokemon:6,value:108.2,owned:2,language:'English',condition:'Near Mint',grade:'Ungraded',year:2023},
{id:'mew',name:'Mew ex',number:'205',set:'Scarlet & Violet 151',rarity:'Hyper Rare',pokemon:151,value:32.4,owned:1,language:'English',condition:'Near Mint',grade:'Ungraded',year:2023},
{id:'pikachu',name:'Pikachu',number:'173',set:'Scarlet & Violet 151',rarity:'Illustration Rare',pokemon:25,value:24.8,owned:3,language:'English',condition:'Near Mint',grade:'Ungraded',year:2023},
{id:'gengar',name:'Gengar VMAX',number:'271',set:'Fusion Strike',rarity:'Secret Rare',pokemon:94,value:286,owned:1,language:'English',condition:'Near Mint',grade:'PSA 10',year:2021},
{id:'bulbasaur',name:'Bulbasaur',number:'166',set:'Scarlet & Violet 151',rarity:'Illustration Rare',pokemon:1,value:26.5,owned:1,language:'Japanese',condition:'Near Mint',grade:'Ungraded',year:2023},
{id:'squirtle',name:'Squirtle',number:'170',set:'Scarlet & Violet 151',rarity:'Illustration Rare',pokemon:7,value:29.9,owned:1,language:'English',condition:'Excellent',grade:'Ungraded',year:2023},
{id:'eevee',name:'Eevee',number:'TG11',set:'Brilliant Stars',rarity:'Trainer Gallery',pokemon:133,value:4.8,owned:2,language:'English',condition:'Near Mint',grade:'Ungraded',year:2022},
{id:'umbreon',name:'Umbreon VMAX',number:'215',set:'Evolving Skies',rarity:'Secret Rare',pokemon:133,value:942,owned:1,language:'English',condition:'Near Mint',grade:'PSA 10',year:2021},
{id:'mewtwo',name:'Mewtwo V',number:'SWSH242',set:'Sword & Shield Promos',rarity:'Promo',pokemon:150,value:18.5,owned:1,language:'English',condition:'Excellent',grade:'Ungraded',year:2022},
{id:'dragonite',name:'Dragonite V',number:'192',set:'Evolving Skies',rarity:'Ultra Rare',pokemon:149,value:176,owned:0,language:'English',condition:'Near Mint',grade:'Ungraded',year:2021},
{id:'venusaur',name:'Venusaur ex',number:'198',set:'Scarlet & Violet 151',rarity:'Special Illustration Rare',pokemon:3,value:51.2,owned:1,language:'English',condition:'Near Mint',grade:'Ungraded',year:2023},
{id:'blastoise',name:'Blastoise ex',number:'200',set:'Scarlet & Violet 151',rarity:'Special Illustration Rare',pokemon:9,value:59.5,owned:0,language:'English',condition:'Near Mint',grade:'Ungraded',year:2023}];
export const pokemon=[
[1,'Bulbasaur','Grass'],[2,'Ivysaur','Grass'],[3,'Venusaur','Grass'],[4,'Charmander','Fire'],[5,'Charmeleon','Fire'],[6,'Charizard','Fire'],[7,'Squirtle','Water'],[8,'Wartortle','Water'],[9,'Blastoise','Water'],[10,'Caterpie','Bug'],[11,'Metapod','Bug'],[12,'Butterfree','Bug'],[25,'Pikachu','Electric'],[94,'Gengar','Ghost'],[133,'Eevee','Normal'],[137,'Porygon','Normal'],[142,'Aerodactyl','Rock'],[144,'Articuno','Ice'],[145,'Zapdos','Electric'],[146,'Moltres','Fire'],[149,'Dragonite','Dragon'],[150,'Mewtwo','Psychic'],[151,'Mew','Psychic'],[152,'Chikorita','Grass'],[155,'Cyndaquil','Fire'],[158,'Totodile','Water'],[252,'Treecko','Grass'],[255,'Torchic','Fire'],[258,'Mudkip','Water']].map(([id,name,type])=>({id:Number(id),name:String(name),type:String(type),owned:![9,137,142,144,145,146,149].includes(Number(id))}));
export const paths=[{id:'kanto',name:'Kanto Living Dex',current:143,total:151,portraits:[1,4,7],caption:'One of every Pokémon. Where it all began.'},{id:'eevee',name:'Eeveelution Collection',current:37,total:52,portraits:[133],caption:'Every evolution. Every little personality.'},{id:'charizard',name:'Charizard Collection',current:18,total:126,portraits:[6],caption:'A collection with a little more fire.'},{id:'151',name:'151 Master Set',current:187,total:207,portraits:[151],caption:'Your original adventure, complete.'}];
export const generations=[{name:'Kanto',current:143,total:151,portrait:1,range:[1,151]},{name:'Johto',current:81,total:100,portrait:152,range:[152,251]},{name:'Hoenn',current:96,total:135,portrait:252,range:[252,386]}];
export const initialCopies=Object.fromEntries(cards.map(c=>[c.id,c.owned]));
