"""Subset the existing licensed Onest font; inline it so first paint never uses a substitute.
Run with fonttools[woff] available. Build consumes the checked-in CSS, not this utility.
"""
from fontTools import subset
from fontTools.ttLib import TTFont
from io import BytesIO
import base64
font = TTFont('public/fonts/onest.ttf')
options = subset.Options()
options.flavor = 'woff2'
options.recommended_glyphs = True
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes=list(range(0x20, 0x180)) + list(range(0x2000, 0x2070)) + [0x20ac, 0x2192])
subsetter.subset(font)
font.flavor = 'woff2'
buffer = BytesIO()
font.save(buffer)
data = base64.b64encode(buffer.getvalue()).decode()
with open('src/app/onest-critical.css', 'w') as output:
    output.write('/* Existing Onest, Latin subset. License: public/fonts/OFL.txt. Generated by prepare-first-paint-font.py. */\n')
    output.write('@font-face{font-family:Onest;src:url(data:font/woff2;base64,' + data + ') format("woff2");font-weight:100 900;font-style:normal;font-display:block}\n')
    output.write(':root{--font-onest:Onest}\n')
print('Critical font:', len(buffer.getvalue()), 'bytes')
