// node scripts/prepare-sets.mjs
// Set logos for the catalogue section, English and Japanese, from MonDex's own
// API (our S3 copies where there are any). Trimmed, 80 px tall WebP with
// transparency, plus src/home/sets.ts with their sizes and the set counts.
// Logos are Pokémon trademarks, shown like the card pictures: to name the sets
// the app knows.
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';

const API = 'https://mondex-api.onrender.com/api/v1/cards/sets';
const EN = [
  'base1',
  'sv8pt5',
  'base5',
  'swsh7',
  'neo1',
  'sv3pt5',
  'base2',
  'sm115',
  'cel25',
  'sv6',
  'base3',
  'swsh12pt5',
  'ecard3',
  'sv4pt5',
  'me2',
  'hgss1',
  'sv10',
  'xy12',
  'swsh9',
  'me2pt5',
  'sv8',
  'swsh11',
  'ex16',
  'sv9',
  'swsh45',
  'me1',
  'sm12',
  'gym1',
];
const JA = [
  'ja-23599',
  'ja-23601',
  'ja-24349',
  'ja-24350',
  'ja-24499',
  'ja-23909',
  'ja-24399',
  'ja-24400',
  'ja-24459',
  'ja-24600',
  'ja-24653',
  'ja-24711',
  'ja-24791',
  'ja-24173',
  'ja-24260',
  'ja-23604',
  'ja-23603',
  'ja-23602',
  'ja-23600',
  'ja-23609',
  'ja-23605',
  'ja-23606',
  'ja-23708',
  'ja-23709',
  'ja-23777',
  'ja-23615',
];
const HEIGHT = 80;
const MAX_WIDTH = 330;

const list = async (language) => {
  const response = await fetch(`${API}?language=${language}&limit=1000`);
  if (!response.ok) throw new Error(`${language} sets: ${response.status}`);
  return response.json();
};
const [en, ja] = await Promise.all([list('en'), list('ja')]);
const byId = new Map([...en, ...ja].map((s) => [s.id, s]));
await mkdir('public/assets/sets', { recursive: true });

async function logo(id) {
  const set = byId.get(id);
  const url = set?.backup_logo_image_url || set?.logo_image_url;
  if (!url) throw new Error(`${id}: no logo`);
  const response = await fetch(url, { headers: { 'User-Agent': 'MonDex website build' } });
  if (!response.ok) throw new Error(`${id}: ${response.status}`);
  const input = Buffer.from(await response.arrayBuffer());
  const file = `public/assets/sets/${id}.webp`;
  const info = await sharp(input)
    .trim({ threshold: 1 })
    .resize({ height: HEIGHT, width: MAX_WIDTH, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 76, alphaQuality: 80, effort: 6 })
    .toFile(file);
  return [id, set.name, info.width, info.height];
}
const english = [];
for (const id of EN) english.push(await logo(id));
const japanese = [];
for (const id of JA) japanese.push(await logo(id));
// Counts rounded down to a tens figure, so the page stays true as sets are added.
const floor = (n) => Math.floor(n / 10) * 10;
const source = `// Generated by scripts/prepare-sets.mjs: [id, name, width, height] of each logo.
export const SET_COUNTS = { en: ${floor(en.length)}, ja: ${floor(ja.length)} };
export const EN_SETS: [string, string, number, number][] = ${JSON.stringify(english)};
export const JA_SETS: [string, string, number, number][] = ${JSON.stringify(japanese)};
`;
await writeFile('src/home/sets.ts', source);
console.log(
  `en ${en.length} sets, ja ${ja.length} sets, ${english.length + japanese.length} logos`,
);
