// Public catalogue identities; source records in /assets/catalogue-provenance.json.
export const additionalCards = [
  {
    id: 'rayquaza',
    name: 'Rayquaza VMAX',
    set: 'Evolving Skies',
    number: '218/203',
    artist: 'Anesaki Dynamic',
    setId: 'swsh7',
  },
  {
    id: 'giratina',
    name: 'Giratina V',
    set: 'Lost Origin',
    number: '186/196',
    artist: 'Shinji Kanda',
    setId: 'swsh11',
  },
  {
    id: 'lugia',
    name: 'Lugia',
    set: 'Neo Genesis',
    number: '9/111',
    artist: 'Hironobu Yoshida',
    setId: 'neo1',
  },
  {
    id: 'blaziken',
    name: 'Blaziken VMAX',
    set: 'Chilling Reign',
    number: '201/198',
    artist: 'Shigenori Negishi',
    setId: 'swsh6',
  },
  {
    id: 'dialga',
    name: 'Origin Forme Dialga V',
    set: 'Astral Radiance',
    number: '177/189',
    artist: 'Mitsuhiro Arita',
    setId: 'swsh10',
  },
  {
    id: 'leafeon',
    name: 'Leafeon VSTAR',
    set: 'Crown Zenith Galarian Gallery',
    number: 'GG35/GG70',
    artist: 'Jiro Sasumo',
    setId: 'swsh12pt5gg',
  },
  {
    id: 'magikarp',
    name: 'Magikarp',
    set: 'Paldea Evolved',
    number: '203/193',
    artist: 'Shinji Kanda',
    setId: 'sv2',
  },
  {
    id: 'gardevoir',
    name: 'Gardevoir ex',
    set: 'Scarlet & Violet',
    number: '245/198',
    artist: 'Jiro Sasumo',
    setId: 'sv1',
  },
  {
    id: 'houndour',
    name: 'Houndour',
    set: 'Obsidian Flames',
    number: '204/197',
    artist: 'KYUPIYAMA',
    setId: 'sv3',
  },
  {
    id: 'iron-leaves',
    name: 'Iron Leaves ex',
    set: 'Temporal Forces',
    number: '203/162',
    artist: 'nagimiso',
    setId: 'sv5',
  },
  {
    id: 'groudon',
    name: 'Groudon',
    set: 'Paradox Rift',
    number: '199/182',
    artist: 'Nurikabe',
    setId: 'sv4',
  },
  {
    id: 'tyranitar',
    name: 'Tyranitar V',
    set: 'Battle Styles',
    number: '155/163',
    artist: 'HYOGONOSUKE',
    setId: 'swsh5',
  },
  {
    id: 'sylveon',
    name: 'Sylveon VMAX',
    set: 'Evolving Skies',
    number: '212/203',
    artist: 'Taira Akitsu',
    setId: 'swsh7',
  },
  {
    id: 'aerodactyl',
    name: 'Aerodactyl V',
    set: 'Lost Origin',
    number: '180/196',
    artist: 'Nurikabe',
    setId: 'swsh11',
  },
  {
    id: 'arceus',
    name: 'Arceus V',
    set: 'Brilliant Stars',
    number: '166/172',
    artist: 'kawayoo',
    setId: 'swsh9',
  },
  {
    id: 'suicune',
    name: 'Suicune V',
    set: 'Crown Zenith Galarian Gallery',
    number: 'GG38/GG70',
    artist: 'Atsushi Furusawa',
    setId: 'swsh12pt5gg',
  },
  {
    id: 'reshiram',
    name: 'Reshiram',
    set: 'Black & White',
    number: '113/114',
    artist: '5ban Graphics',
    setId: 'bw1',
  },
  {
    id: 'xerneas',
    name: 'Xerneas-EX',
    set: 'XY',
    number: '146/146',
    artist: '5ban Graphics',
    setId: 'xy1',
  },
];
export const discoveryPokemon = [
  {
    id: 54,
    name: 'Psyduck',
  },
  {
    id: 94,
    name: 'Gengar',
  },
  {
    id: 143,
    name: 'Snorlax',
  },
  {
    id: 155,
    name: 'Cyndaquil',
  },
  {
    id: 175,
    name: 'Togepi',
  },
  {
    id: 249,
    name: 'Lugia',
  },
  {
    id: 258,
    name: 'Mudkip',
  },
  {
    id: 282,
    name: 'Gardevoir',
  },
  {
    id: 384,
    name: 'Rayquaza',
  },
  {
    id: 393,
    name: 'Piplup',
  },
  {
    id: 448,
    name: 'Lucario',
  },
  {
    id: 470,
    name: 'Leafeon',
  },
  {
    id: 495,
    name: 'Snivy',
  },
  {
    id: 570,
    name: 'Zorua',
  },
  {
    id: 607,
    name: 'Litwick',
  },
  {
    id: 658,
    name: 'Greninja',
  },
  {
    id: 700,
    name: 'Sylveon',
  },
  {
    id: 722,
    name: 'Rowlet',
  },
  {
    id: 778,
    name: 'Mimikyu',
  },
  {
    id: 813,
    name: 'Scorbunny',
  },
  {
    id: 887,
    name: 'Dragapult',
  },
  {
    id: 906,
    name: 'Sprigatito',
  },
  {
    id: 909,
    name: 'Fuecoco',
  },
  {
    id: 959,
    name: 'Tinkaton',
  },
];
export const catalogueSets = [
  {
    id: 'base1',
    name: 'Base',
    series: 'Base',
    year: '1999',
  },
  {
    id: 'base2',
    name: 'Jungle',
    series: 'Base',
    year: '1999',
  },
  {
    id: 'basep',
    name: 'Wizards Black Star Promos',
    series: 'Base',
    year: '1999',
  },
  {
    id: 'base3',
    name: 'Fossil',
    series: 'Base',
    year: '1999',
  },
  {
    id: 'base4',
    name: 'Base Set 2',
    series: 'Base',
    year: '2000',
  },
  {
    id: 'base5',
    name: 'Team Rocket',
    series: 'Base',
    year: '2000',
  },
  {
    id: 'gym1',
    name: 'Gym Heroes',
    series: 'Gym',
    year: '2000',
  },
  {
    id: 'gym2',
    name: 'Gym Challenge',
    series: 'Gym',
    year: '2000',
  },
  {
    id: 'neo1',
    name: 'Neo Genesis',
    series: 'Neo',
    year: '2000',
  },
  {
    id: 'neo2',
    name: 'Neo Discovery',
    series: 'Neo',
    year: '2001',
  },
  {
    id: 'si1',
    name: 'Southern Islands',
    series: 'Other',
    year: '2001',
  },
  {
    id: 'neo3',
    name: 'Neo Revelation',
    series: 'Neo',
    year: '2001',
  },
  {
    id: 'neo4',
    name: 'Neo Destiny',
    series: 'Neo',
    year: '2002',
  },
  {
    id: 'base6',
    name: 'Legendary Collection',
    series: 'Other',
    year: '2002',
  },
  {
    id: 'ecard1',
    name: 'Expedition Base Set',
    series: 'E-Card',
    year: '2002',
  },
  {
    id: 'bp',
    name: 'Best of Game',
    series: 'Other',
    year: '2002',
  },
  {
    id: 'ecard2',
    name: 'Aquapolis',
    series: 'E-Card',
    year: '2003',
  },
  {
    id: 'ecard3',
    name: 'Skyridge',
    series: 'E-Card',
    year: '2003',
  },
  {
    id: 'ex1',
    name: 'Ruby & Sapphire',
    series: 'EX',
    year: '2003',
  },
  {
    id: 'ex2',
    name: 'Sandstorm',
    series: 'EX',
    year: '2003',
  },
  {
    id: 'ex3',
    name: 'Dragon',
    series: 'EX',
    year: '2003',
  },
  {
    id: 'np',
    name: 'Nintendo Black Star Promos',
    series: 'NP',
    year: '2003',
  },
  {
    id: 'ex4',
    name: 'Team Magma vs Team Aqua',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'tk1a',
    name: 'EX Trainer Kit Latias',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'tk1b',
    name: 'EX Trainer Kit Latios',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'ex5',
    name: 'Hidden Legends',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'ex6',
    name: 'FireRed & LeafGreen',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'pop1',
    name: 'POP Series 1',
    series: 'POP',
    year: '2004',
  },
  {
    id: 'ex7',
    name: 'Team Rocket Returns',
    series: 'EX',
    year: '2004',
  },
  {
    id: 'ex8',
    name: 'Deoxys',
    series: 'EX',
    year: '2005',
  },
  {
    id: 'ex9',
    name: 'Emerald',
    series: 'EX',
    year: '2005',
  },
  {
    id: 'ex10',
    name: 'Unseen Forces',
    series: 'EX',
    year: '2005',
  },
  {
    id: 'pop2',
    name: 'POP Series 2',
    series: 'POP',
    year: '2005',
  },
  {
    id: 'ex11',
    name: 'Delta Species',
    series: 'EX',
    year: '2005',
  },
  {
    id: 'ex12',
    name: 'Legend Maker',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'tk2a',
    name: 'EX Trainer Kit 2 Plusle',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'tk2b',
    name: 'EX Trainer Kit 2 Minun',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'pop3',
    name: 'POP Series 3',
    series: 'POP',
    year: '2006',
  },
  {
    id: 'ex13',
    name: 'Holon Phantoms',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'ex14',
    name: 'Crystal Guardians',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'pop4',
    name: 'POP Series 4',
    series: 'POP',
    year: '2006',
  },
  {
    id: 'ex15',
    name: 'Dragon Frontiers',
    series: 'EX',
    year: '2006',
  },
  {
    id: 'pop5',
    name: 'POP Series 5',
    series: 'POP',
    year: '2007',
  },
  {
    id: 'ex16',
    name: 'Power Keepers',
    series: 'EX',
    year: '2007',
  },
  {
    id: 'dp1',
    name: 'Diamond & Pearl',
    series: 'Diamond & Pearl',
    year: '2007',
  },
  {
    id: 'dpp',
    name: 'DP Black Star Promos',
    series: 'Diamond & Pearl',
    year: '2007',
  },
  {
    id: 'dp2',
    name: 'Mysterious Treasures',
    series: 'Diamond & Pearl',
    year: '2007',
  },
  {
    id: 'pop6',
    name: 'POP Series 6',
    series: 'POP',
    year: '2007',
  },
  {
    id: 'dp3',
    name: 'Secret Wonders',
    series: 'Diamond & Pearl',
    year: '2007',
  },
  {
    id: 'dp4',
    name: 'Great Encounters',
    series: 'Diamond & Pearl',
    year: '2008',
  },
  {
    id: 'pop7',
    name: 'POP Series 7',
    series: 'POP',
    year: '2008',
  },
  {
    id: 'dp5',
    name: 'Majestic Dawn',
    series: 'Diamond & Pearl',
    year: '2008',
  },
  {
    id: 'dp6',
    name: 'Legends Awakened',
    series: 'Diamond & Pearl',
    year: '2008',
  },
  {
    id: 'pop8',
    name: 'POP Series 8',
    series: 'POP',
    year: '2008',
  },
  {
    id: 'dp7',
    name: 'Stormfront',
    series: 'Diamond & Pearl',
    year: '2008',
  },
  {
    id: 'pl1',
    name: 'Platinum',
    series: 'Platinum',
    year: '2009',
  },
  {
    id: 'pop9',
    name: 'POP Series 9',
    series: 'POP',
    year: '2009',
  },
  {
    id: 'pl2',
    name: 'Rising Rivals',
    series: 'Platinum',
    year: '2009',
  },
  {
    id: 'pl3',
    name: 'Supreme Victors',
    series: 'Platinum',
    year: '2009',
  },
  {
    id: 'pl4',
    name: 'Arceus',
    series: 'Platinum',
    year: '2009',
  },
  {
    id: 'ru1',
    name: 'Pok\u00e9mon Rumble',
    series: 'Other',
    year: '2009',
  },
  {
    id: 'hgss1',
    name: 'HeartGold & SoulSilver',
    series: 'HeartGold & SoulSilver',
    year: '2010',
  },
  {
    id: 'hsp',
    name: 'HGSS Black Star Promos',
    series: 'HeartGold & SoulSilver',
    year: '2010',
  },
  {
    id: 'hgss2',
    name: 'HS\u2014Unleashed',
    series: 'HeartGold & SoulSilver',
    year: '2010',
  },
  {
    id: 'hgss3',
    name: 'HS\u2014Undaunted',
    series: 'HeartGold & SoulSilver',
    year: '2010',
  },
  {
    id: 'hgss4',
    name: 'HS\u2014Triumphant',
    series: 'HeartGold & SoulSilver',
    year: '2010',
  },
  {
    id: 'col1',
    name: 'Call of Legends',
    series: 'HeartGold & SoulSilver',
    year: '2011',
  },
  {
    id: 'bwp',
    name: 'BW Black Star Promos',
    series: 'Black & White',
    year: '2011',
  },
  {
    id: 'bw1',
    name: 'Black & White',
    series: 'Black & White',
    year: '2011',
  },
  {
    id: 'mcd11',
    name: "McDonald's Collection 2011",
    series: 'Other',
    year: '2011',
  },
  {
    id: 'bw2',
    name: 'Emerging Powers',
    series: 'Black & White',
    year: '2011',
  },
  {
    id: 'bw3',
    name: 'Noble Victories',
    series: 'Black & White',
    year: '2011',
  },
  {
    id: 'bw4',
    name: 'Next Destinies',
    series: 'Black & White',
    year: '2012',
  },
  {
    id: 'bw5',
    name: 'Dark Explorers',
    series: 'Black & White',
    year: '2012',
  },
  {
    id: 'mcd12',
    name: "McDonald's Collection 2012",
    series: 'Other',
    year: '2012',
  },
  {
    id: 'bw6',
    name: 'Dragons Exalted',
    series: 'Black & White',
    year: '2012',
  },
  {
    id: 'dv1',
    name: 'Dragon Vault',
    series: 'Black & White',
    year: '2012',
  },
  {
    id: 'bw7',
    name: 'Boundaries Crossed',
    series: 'Black & White',
    year: '2012',
  },
  {
    id: 'bw8',
    name: 'Plasma Storm',
    series: 'Black & White',
    year: '2013',
  },
  {
    id: 'bw9',
    name: 'Plasma Freeze',
    series: 'Black & White',
    year: '2013',
  },
  {
    id: 'bw10',
    name: 'Plasma Blast',
    series: 'Black & White',
    year: '2013',
  },
  {
    id: 'xyp',
    name: 'XY Black Star Promos',
    series: 'XY',
    year: '2013',
  },
  {
    id: 'bw11',
    name: 'Legendary Treasures',
    series: 'Black & White',
    year: '2013',
  },
  {
    id: 'xy0',
    name: 'Kalos Starter Set',
    series: 'XY',
    year: '2013',
  },
  {
    id: 'xy1',
    name: 'XY',
    series: 'XY',
    year: '2014',
  },
  {
    id: 'xy2',
    name: 'Flashfire',
    series: 'XY',
    year: '2014',
  },
  {
    id: 'mcd14',
    name: "McDonald's Collection 2014",
    series: 'Other',
    year: '2014',
  },
  {
    id: 'xy3',
    name: 'Furious Fists',
    series: 'XY',
    year: '2014',
  },
  {
    id: 'xy4',
    name: 'Phantom Forces',
    series: 'XY',
    year: '2014',
  },
  {
    id: 'xy5',
    name: 'Primal Clash',
    series: 'XY',
    year: '2015',
  },
  {
    id: 'dc1',
    name: 'Double Crisis',
    series: 'XY',
    year: '2015',
  },
  {
    id: 'xy6',
    name: 'Roaring Skies',
    series: 'XY',
    year: '2015',
  },
  {
    id: 'xy7',
    name: 'Ancient Origins',
    series: 'XY',
    year: '2015',
  },
  {
    id: 'xy8',
    name: 'BREAKthrough',
    series: 'XY',
    year: '2015',
  },
  {
    id: 'mcd15',
    name: "McDonald's Collection 2015",
    series: 'Other',
    year: '2015',
  },
  {
    id: 'xy9',
    name: 'BREAKpoint',
    series: 'XY',
    year: '2016',
  },
  {
    id: 'g1',
    name: 'Generations',
    series: 'XY',
    year: '2016',
  },
  {
    id: 'xy10',
    name: 'Fates Collide',
    series: 'XY',
    year: '2016',
  },
  {
    id: 'xy11',
    name: 'Steam Siege',
    series: 'XY',
    year: '2016',
  },
  {
    id: 'mcd16',
    name: "McDonald's Collection 2016",
    series: 'Other',
    year: '2016',
  },
  {
    id: 'xy12',
    name: 'Evolutions',
    series: 'XY',
    year: '2016',
  },
  {
    id: 'sm1',
    name: 'Sun & Moon',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'smp',
    name: 'SM Black Star Promos',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'sm2',
    name: 'Guardians Rising',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'sm3',
    name: 'Burning Shadows',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'sm35',
    name: 'Shining Legends',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'sm4',
    name: 'Crimson Invasion',
    series: 'Sun & Moon',
    year: '2017',
  },
  {
    id: 'mcd17',
    name: "McDonald's Collection 2017",
    series: 'Other',
    year: '2017',
  },
  {
    id: 'sm5',
    name: 'Ultra Prism',
    series: 'Sun & Moon',
    year: '2018',
  },
  {
    id: 'sm6',
    name: 'Forbidden Light',
    series: 'Sun & Moon',
    year: '2018',
  },
  {
    id: 'sm7',
    name: 'Celestial Storm',
    series: 'Sun & Moon',
    year: '2018',
  },
  {
    id: 'sm75',
    name: 'Dragon Majesty',
    series: 'Sun & Moon',
    year: '2018',
  },
  {
    id: 'mcd18',
    name: "McDonald's Collection 2018",
    series: 'Other',
    year: '2018',
  },
  {
    id: 'sm8',
    name: 'Lost Thunder',
    series: 'Sun & Moon',
    year: '2018',
  },
  {
    id: 'sm9',
    name: 'Team Up',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'det1',
    name: 'Detective Pikachu',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'sm10',
    name: 'Unbroken Bonds',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'sm11',
    name: 'Unified Minds',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'sm115',
    name: 'Hidden Fates',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'sma',
    name: 'Hidden Fates Shiny Vault',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'mcd19',
    name: "McDonald's Collection 2019",
    series: 'Other',
    year: '2019',
  },
  {
    id: 'sm12',
    name: 'Cosmic Eclipse',
    series: 'Sun & Moon',
    year: '2019',
  },
  {
    id: 'swshp',
    name: 'SWSH Black Star Promos',
    series: 'Sword & Shield',
    year: '2019',
  },
  {
    id: 'swsh1',
    name: 'Sword & Shield',
    series: 'Sword & Shield',
    year: '2020',
  },
  {
    id: 'swsh2',
    name: 'Rebel Clash',
    series: 'Sword & Shield',
    year: '2020',
  },
  {
    id: 'swsh3',
    name: 'Darkness Ablaze',
    series: 'Sword & Shield',
    year: '2020',
  },
  {
    id: 'fut20',
    name: 'Pok\u00e9mon Futsal Collection',
    series: 'Other',
    year: '2020',
  },
  {
    id: 'swsh35',
    name: "Champion's Path",
    series: 'Sword & Shield',
    year: '2020',
  },
  {
    id: 'swsh4',
    name: 'Vivid Voltage',
    series: 'Sword & Shield',
    year: '2020',
  },
  {
    id: 'swsh45',
    name: 'Shining Fates',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh45sv',
    name: 'Shining Fates Shiny Vault',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh5',
    name: 'Battle Styles',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh6',
    name: 'Chilling Reign',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh7',
    name: 'Evolving Skies',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'mcd21',
    name: "McDonald's Collection 2021",
    series: 'Other',
    year: '2021',
  },
  {
    id: 'cel25',
    name: 'Celebrations',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'cel25c',
    name: 'Celebrations: Classic Collection',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh8',
    name: 'Fusion Strike',
    series: 'Sword & Shield',
    year: '2021',
  },
  {
    id: 'swsh9',
    name: 'Brilliant Stars',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh9tg',
    name: 'Brilliant Stars Trainer Gallery',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh10',
    name: 'Astral Radiance',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh10tg',
    name: 'Astral Radiance Trainer Gallery',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'pgo',
    name: 'Pok\u00e9mon GO',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'mcd22',
    name: "McDonald's Collection 2022",
    series: 'Other',
    year: '2022',
  },
  {
    id: 'swsh11',
    name: 'Lost Origin',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh11tg',
    name: 'Lost Origin Trainer Gallery',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh12',
    name: 'Silver Tempest',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh12tg',
    name: 'Silver Tempest Trainer Gallery',
    series: 'Sword & Shield',
    year: '2022',
  },
  {
    id: 'swsh12pt5',
    name: 'Crown Zenith',
    series: 'Sword & Shield',
    year: '2023',
  },
  {
    id: 'swsh12pt5gg',
    name: 'Crown Zenith Galarian Gallery',
    series: 'Sword & Shield',
    year: '2023',
  },
  {
    id: 'svp',
    name: 'Scarlet & Violet Black Star Promos',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sve',
    name: 'Scarlet & Violet Energies',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv1',
    name: 'Scarlet & Violet',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv2',
    name: 'Paldea Evolved',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv3',
    name: 'Obsidian Flames',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv3pt5',
    name: '151',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv4',
    name: 'Paradox Rift',
    series: 'Scarlet & Violet',
    year: '2023',
  },
  {
    id: 'sv4pt5',
    name: 'Paldean Fates',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv5',
    name: 'Temporal Forces',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv6',
    name: 'Twilight Masquerade',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv6pt5',
    name: 'Shrouded Fable',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv7',
    name: 'Stellar Crown',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv8',
    name: 'Surging Sparks',
    series: 'Scarlet & Violet',
    year: '2024',
  },
  {
    id: 'sv8pt5',
    name: 'Prismatic Evolutions',
    series: 'Scarlet & Violet',
    year: '2025',
  },
  {
    id: 'sv9',
    name: 'Journey Together',
    series: 'Scarlet & Violet',
    year: '2025',
  },
  {
    id: 'sv10',
    name: 'Destined Rivals',
    series: 'Scarlet & Violet',
    year: '2025',
  },
  {
    id: 'zsv10pt5',
    name: 'Black Bolt',
    series: 'Scarlet & Violet',
    year: '2025',
  },
  {
    id: 'rsv10pt5',
    name: 'White Flare',
    series: 'Scarlet & Violet',
    year: '2025',
  },
  {
    id: 'me1',
    name: 'Mega Evolution',
    series: 'Mega Evolution',
    year: '2025',
  },
  {
    id: 'me2',
    name: 'Phantasmal Flames',
    series: 'Mega Evolution',
    year: '2025',
  },
  {
    id: 'me2pt5',
    name: 'Ascended Heroes',
    series: 'Mega Evolution',
    year: '2026',
  },
  {
    id: 'me3',
    name: 'Perfect Order',
    series: 'Mega Evolution',
    year: '2026',
  },
  {
    id: 'me4',
    name: 'Chaos Rising',
    series: 'Mega Evolution',
    year: '2026',
  },
  {
    id: 'me5',
    name: 'Pitch Black',
    series: 'Mega Evolution',
    year: '2026',
  },
];
