// Every word on the home page, English (US) and German.
export const homeCopy = {
  en: {
    meta: {
      title: 'MonDex – Scan your cards. Complete your Pokédex.',
      description:
        'The Pokémon card app built around discovery. Scan a card and its Pokémon takes its place in your Pokédex. Coming to iPhone first.',
    },
    nav: { scan: 'Scan', dex: 'Pokédex', collection: 'Collection', faq: 'FAQ', cta: 'Join the waitlist' },
    hero: {
      eyebrow: 'Coming to iPhone first',
      title: ['Scan your cards.', 'Complete your Pokédex.'],
      body: 'Every card you scan brings a Pokémon into your Pokédex. See who you have found, and who is still out there.',
    },
    phone: {
      simulated: 'Simulated screen',
      estimated: 'Estimated value',
      price: '$352',
      matched: 'Matched card',
      set: 'Scarlet & Violet 151 · 199',
      discovery: 'New in your Pokédex',
      modes: ['Snap', 'Auto', 'Batch'],
      dex: 'Dex',
      tabs: ['Pokémon', 'Paths', 'Generations'],
      search: 'Name or Pokédex number',
      total: '1025 Pokémon',
      undiscovered: 'Undiscovered',
      names: ['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod', 'Butterfree'],
      bar: ['Home', 'Dex', 'Scan', 'Cards', 'Value'],
    },
    scan: {
      eyebrow: 'Scanning',
      title: ['Point your phone.', 'That’s it.'],
      body: 'MonDex recognises the card while you hold it in the frame. One card, or a whole stack in a row.',
      facts: [
        ['Hands-free', 'In Auto mode there is nothing to press. Hold a card in the frame, then the next.'],
        ['Offline', 'Keeps scanning at a card show with no signal.', 1],
        ['Exact', 'Knows every printing, down to Poké Ball and Master Ball patterns.', 2],
      ],
    },
    dex: {
      eyebrow: 'Your Pokédex',
      title: ['Every Pokémon you own.', 'Every one still out there.'],
      body: 'Collecting is finding. Each new Pokémon takes its place, and the next one is already waiting.',
      count: 'of 1,025 discovered',
    },
    collection: {
      eyebrow: 'Your collection',
      title: ['Your cards.', 'Your rules.'],
      sets: ['Finish a set', 'See exactly which cards are missing from every set you have started.'],
      values: ['Values, when you want them', 'Track what your cards are worth, or hide every price and collect for the joy of it.'],
      valuesToggle: 'Show values',
      goals: ['Goals worth chasing', 'A Living Dex, every Charizard, a whole type. Pick a goal and every card moves you closer.'],
      goalItems: [
        ['Kanto Living Dex', '142 / 151'],
        ['Charizard collection', '18 / 25'],
        ['Fire collection', 'Earned'],
      ],
      setName: 'Pokémon 151',
      setProgress: '148 / 165',
    },
    shelf: {
      eyebrow: 'The catalogue',
      title: ['Every card.', 'Every set.'],
      body: 'More than 20,000 cards across every English set, from the 1999 Base Set to the latest release.',
    },
    openings: {
      eyebrow: 'Pack openings',
      title: ['Open a pack.', 'See how it went.'],
      body: 'Scan your pulls in Opening mode and add what the pack cost. MonDex sets what you paid beside what came out.',
      paid: 'You paid',
      pulled: 'Came out',
      more: '+ 9 more cards',
      result: 'Difference',
      values: ['$5.49', '$38.70', '+$33.21'],
    },
    gallery: {
      eyebrow: 'A closer look',
      title: 'Made for collectors. Down to the details.',
      shots: ['Home', 'Pokédex', 'Your cards', 'A card, up close'],
    },
    faq: {
      title: 'Questions',
      items: [
        ['When is MonDex coming?', 'MonDex is in development and launches on iPhone first, with Android to follow. Join the waitlist and we will email you once, on launch day.'],
        ['Which languages does it speak?', 'The app is in English and German. Its catalogue holds the English cards: a card printed in another language is often recognised by its artwork and saved as its English counterpart, with your copy’s language noted. Japanese-only cards are not in the catalogue yet, and card names are shown in English.'],
        ['Which cards does it know?', 'Every English Pokémon card set, from the 1999 Base Set to the newest release, including special printings like Poké Ball and Master Ball patterns.'],
        ['Can I scan without a connection?', 'Yes. With the offline pack downloaded, MonDex recognises cards without a connection and syncs them when you are back online.'],
        ['Can I bring my existing collection?', 'Scan it in: Batch takes up to a hundred cards in one session, and nothing is saved until you have checked them.'],
      ],
    },
    waitlist: {
      title: ['Your next discovery.', 'Worth the wait.'],
      body: 'One email on launch day. Nothing else.',
      email: 'Email address',
      action: 'Join the waitlist',
      sending: 'Joining…',
      proof: '{n}+ collectors are already waiting.',
      success: 'You’re on the list.',
      successBody: 'We’ll email you when MonDex is ready.',
      emailError: 'Please enter a valid email address.',
      rateError: 'Too many attempts. Please try again in a few minutes.',
      serverError: 'That didn’t work. Please try again.',
      consent: 'By joining you agree to one email when MonDex launches. You can withdraw at any time.',
      privacy: 'Privacy',
    },
    footer: {
      tagline: 'Your Pokémon collection. Complete.',
      contact: 'Contact',
      privacy: 'Privacy',
      imprint: 'Legal notice',
      notes: [
        'Offline scanning uses the offline pack, which MonDex downloads while you are online. Without a connection you choose special printings yourself, and prices and syncing wait until you are back online.',
        'Every English printing TCGplayer lists. A pattern is picked out from the photo only when it clearly shows; otherwise you choose it.',
        'Screens are simulated. Prices, progress and counts on this page are examples.',
      ],
      legal:
        'Pokémon and Pokémon card names and images are trademarks of their respective owners. MonDex is an independent project and is not affiliated with Nintendo, Creatures, GAME FREAK or The Pokémon Company.',
    },
    replay: 'Play again',
    menu: ['Open menu', 'Close menu'],
  },
  de: {
    meta: {
      title: 'MonDex – Scanne deine Karten. Vervollständige deinen Pokédex.',
      description:
        'Die Pokémon-Karten-App rund ums Entdecken. Scanne eine Karte, und ihr Pokémon bekommt seinen Platz in deinem Pokédex. Zuerst für das iPhone.',
    },
    nav: { scan: 'Scannen', dex: 'Pokédex', collection: 'Sammlung', faq: 'Fragen', cta: 'Vormerken' },
    hero: {
      eyebrow: 'Zuerst für das iPhone',
      title: ['Scanne deine Karten.', 'Vervollständige deinen Pokédex.'],
      body: 'Jede Karte, die du scannst, bringt ein Pokémon in deinen Pokédex. Sieh, wen du gefunden hast und wer noch da draußen ist.',
    },
    phone: {
      simulated: 'Bildschirm simuliert',
      estimated: 'Geschätzter Wert',
      price: '325 €',
      matched: 'Karte erkannt',
      set: 'Scarlet & Violet 151 · 199',
      discovery: 'Neu in deinem Pokédex',
      modes: ['Snap', 'Auto', 'Stapel'],
      dex: 'Dex',
      tabs: ['Pokémon', 'Sammelziele', 'Generationen'],
      search: 'Name oder Pokédex-Nummer',
      total: '1025 Pokémon',
      undiscovered: 'Unentdeckt',
      names: ['Bisasam', 'Bisaknosp', 'Bisaflor', 'Glumanda', 'Glutexo', 'Glurak', 'Schiggy', 'Schillok', 'Turtok', 'Raupy', 'Safcon', 'Smettbo'],
      bar: ['Start', 'Dex', 'Scannen', 'Karten', 'Wert'],
    },
    scan: {
      eyebrow: 'Scannen',
      title: ['Handy draufhalten.', 'Fertig.'],
      body: 'MonDex erkennt die Karte, während du sie in den Rahmen hältst. Eine Karte oder einen ganzen Stapel am Stück.',
      facts: [
        ['Freihändig', 'Im Auto-Modus drückst du nichts. Karte in den Rahmen halten, dann die nächste.'],
        ['Offline', 'Scannt auf der Tauschbörse weiter, auch ohne Empfang.', 1],
        ['Genau', 'Kennt jede Variante, bis zum Poké-Ball- und Master-Ball-Muster.', 2],
      ],
    },
    dex: {
      eyebrow: 'Dein Pokédex',
      title: ['Jedes Pokémon, das du hast.', 'Jedes, das noch fehlt.'],
      body: 'Sammeln ist Entdecken. Jedes neue Pokémon bekommt seinen Platz, und das nächste wartet schon.',
      count: 'von 1.025 entdeckt',
    },
    collection: {
      eyebrow: 'Deine Sammlung',
      title: ['Deine Karten.', 'Deine Regeln.'],
      sets: ['Sets vervollständigen', 'Sieh genau, welche Karten dir in jedem begonnenen Set noch fehlen.'],
      values: ['Werte, wenn du willst', 'Behalte den Wert deiner Karten im Blick oder blende alle Preise aus und sammle einfach aus Freude.'],
      valuesToggle: 'Werte zeigen',
      goals: ['Ziele, die sich lohnen', 'Ein Living Dex, jedes Glurak, ein ganzer Typ. Wähl ein Ziel, und jede Karte bringt dich näher.'],
      goalItems: [
        ['Kanto Living Dex', '142 / 151'],
        ['Glurak-Sammlung', '18 / 25'],
        ['Feuer-Sammlung', 'Geschafft'],
      ],
      setName: 'Pokémon 151',
      setProgress: '148 / 165',
    },
    shelf: {
      eyebrow: 'Der Katalog',
      title: ['Jede Karte.', 'Jedes Set.'],
      body: 'Über 20.000 Karten aus jedem englischen Set, vom Grundset 1999 bis zur neuesten Erweiterung.',
    },
    openings: {
      eyebrow: 'Pack-Openings',
      title: ['Pack öffnen.', 'Sehen, wie es lief.'],
      body: 'Scanne deine Pulls im Opening-Modus und trag ein, was das Pack gekostet hat. MonDex stellt gegenüber, was du bezahlt hast und was herauskam.',
      paid: 'Bezahlt',
      pulled: 'Herausgekommen',
      more: '+ 9 weitere Karten',
      result: 'Differenz',
      values: ['5,49 €', '38,70 €', '+33,21 €'],
    },
    gallery: {
      eyebrow: 'Genauer hingeschaut',
      title: 'Für Sammler gemacht. Bis ins Detail.',
      shots: ['Start', 'Pokédex', 'Deine Karten', 'Eine Karte, ganz nah'],
    },
    faq: {
      title: 'Fragen',
      items: [
        ['Wann kommt MonDex?', 'MonDex ist in Entwicklung und startet zuerst auf dem iPhone, Android folgt. Trag dich ein, dann schreiben wir dir einmal, am Starttag.'],
        ['Welche Sprachen spricht MonDex?', 'Die App gibt es auf Deutsch und Englisch. Ihr Katalog enthält die englischen Karten: Eine Karte in einer anderen Sprache wird oft an ihrem Artwork erkannt und als englisches Gegenstück gespeichert, mit der Sprache deines Exemplars. Rein japanische Karten sind noch nicht im Katalog, und Kartennamen erscheinen auf Englisch.'],
        ['Welche Karten kennt MonDex?', 'Jedes englische Pokémon-Kartenset, vom Grundset 1999 bis zur neuesten Erweiterung, samt Sonderdrucken wie Poké-Ball- und Master-Ball-Muster.'],
        ['Kann ich ohne Verbindung scannen?', 'Ja. Mit dem Offline-Paket erkennt MonDex Karten auch ohne Verbindung und gleicht sie ab, sobald du wieder online bist.'],
        ['Kann ich meine Sammlung mitnehmen?', 'Scanne sie ein: Der Stapel-Modus nimmt bis zu hundert Karten pro Sitzung, und gespeichert wird erst, wenn du sie geprüft hast.'],
      ],
    },
    waitlist: {
      title: ['Deine nächste Entdeckung.', 'Das Warten lohnt sich.'],
      body: 'Eine E-Mail am Starttag. Sonst nichts.',
      email: 'E-Mail-Adresse',
      action: 'Vormerken',
      sending: 'Wird eingetragen…',
      proof: 'Schon {n}+ Sammler warten.',
      success: 'Du stehst auf der Liste.',
      successBody: 'Wir schreiben dir, sobald MonDex bereit ist.',
      emailError: 'Bitte gib eine gültige E-Mail-Adresse ein.',
      rateError: 'Zu viele Versuche. Bitte versuche es in ein paar Minuten erneut.',
      serverError: 'Das hat nicht geklappt. Bitte versuche es erneut.',
      consent: 'Mit deiner Anmeldung stimmst du einer E-Mail zum Start von MonDex zu. Du kannst jederzeit widerrufen.',
      privacy: 'Datenschutz',
    },
    footer: {
      tagline: 'Deine Pokémon-Sammlung. Komplett.',
      contact: 'Kontakt',
      privacy: 'Datenschutz',
      imprint: 'Impressum',
      notes: [
        'Offline-Scannen nutzt das Offline-Paket, das MonDex lädt, während du online bist. Ohne Verbindung wählst du Sonderdrucke selbst, und Preise sowie Abgleich warten, bis du wieder online bist.',
        'Jede englische Variante, die TCGplayer führt. Ein Muster wird nur dann am Foto erkannt, wenn es deutlich zu sehen ist; sonst wählst du es.',
        'Bildschirme simuliert. Preise, Fortschritte und Zahlen auf dieser Seite sind Beispiele.',
      ],
      legal:
        'Pokémon sowie Namen und Bilder von Pokémon-Karten sind Marken ihrer jeweiligen Inhaber. MonDex ist ein unabhängiges Projekt und steht in keiner Verbindung zu Nintendo, Creatures, GAME FREAK oder The Pokémon Company.',
    },
    replay: 'Nochmal abspielen',
    menu: ['Menü öffnen', 'Menü schließen'],
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends readonly unknown[]
    ? { readonly [K in keyof T]: Widen<T[K]> }
    : { readonly [K in keyof T]: Widen<T[K]> };
export type HomeCopy = Widen<(typeof homeCopy)['en']>;
