// Every word on the home page, English (US) and German. Facts follow the app
// on main (6 Oct 2026); prices, counts and progress in the scenes are examples.
// In `statement`, {card:x} and {orbit} are pictures between words.
export const homeCopy = {
  en: {
    meta: {
      title: 'MonDex: Pokémon Card Scanner, Value & Pokédex App',
      description:
        'Scan Pokémon cards and see what they’re worth instantly: TCGplayer, eBay and Cardmarket prices, English and Japanese cards, and a Pokédex that fills as you collect.',
    },
    skip: 'Skip to content',
    nav: {
      scan: 'Scanner',
      dex: 'Pokédex',
      prices: 'Prices',
      plus: 'Plus',
      faq: 'FAQ',
      cta: 'Get MonDex',
      ctaLive: 'Download',
    },
    hero: {
      badge: 'Pokémon card scanner for iPhone',
      title: ['Scan your cards.', 'Complete your', 'Pokédex.'],
      body: 'Hold a card up to your phone. MonDex knows instantly which one it is, what it’s worth, and which Pokémon it brings to your Dex.',
      chips: [
        ['Charizard ex', 'Added · $352'],
        ['New in your Pokédex', '#006 Charizard'],
        ['Kanto Living Dex', '142 / 151'],
      ],
    },
    home: {
      title: 'Home',
      collection: 'Your collection',
      cards: 'cards',
      pokedex: 'Pokédex',
      edit: 'Edit Home',
      continueLabel: 'Continue collecting',
      path: 'Kanto Living Dex',
      togo: '142 Pokémon to go',
      viewDex: 'View Dex',
      recent: 'Recently Added',
      tabs: ['Home', 'Dex', 'Scan', 'Cards', 'Value'],
    },
    statement: 'Every card {card:umbreon} has a story. MonDex {orbit} keeps it.',
    scan: {
      eyebrow: 'Scanning',
      title: ['Point your phone.', 'That’s it.'],
      points: [
        ['Auto', 'Card after card. Nothing to press.'],
        ['Batch', 'Up to 100 cards, checked before saving.'],
        ['Offline', 'English and Japanese, even with no signal.'],
      ],
      chips: ['Hands-free', 'English & Japanese', 'Works offline'],
      // Measured: card in view to recognised, median ~0.3 s on an iPhone 13
      // (CLAUDE.md, card detector test 1 Oct 2026; newer phones are faster).
      // Keep it a measured number; the device is not named on the page.
      speed: ['0.3', 'Instantly recognised.', 'Typical time from card in view to result.'],
      screen: {
        modes: ['Auto', 'Batch'],
        cards: [
          ['Charizard ex', '151 · 199/165', '$352'],
          ['Mew ex', '151 · 205/165', '$33'],
          ['Pikachu', '151 · 173/165', '$76'],
        ],
        total: ['Auto', '1 card · $352', '2 cards · $385', '3 cards · $461'],
      },
    },
    dex: {
      eyebrow: 'Your Pokédex',
      title: ['Every Pokémon you own.', 'Every one still out there.'],
      body: 'All 1,025 Pokémon, filled in as you collect. Each new one lights up in its place, and the next gap is already waiting.',
      counter: 'of 1,025 discovered',
      fresh: 'New in your Pokédex',
      names: {
        1: 'Bulbasaur',
        4: 'Charmander',
        7: 'Squirtle',
        25: 'Pikachu',
        54: 'Psyduck',
        94: 'Gengar',
        129: 'Magikarp',
        133: 'Eevee',
        143: 'Snorlax',
        149: 'Dragonite',
        150: 'Mewtwo',
        151: 'Mew',
        155: 'Cyndaquil',
        175: 'Togepi',
        197: 'Umbreon',
        249: 'Lugia',
        257: 'Blaziken',
        282: 'Gardevoir',
      } as Record<number, string>,
      undiscovered: 'Undiscovered',
    },
    prices: {
      eyebrow: 'Prices',
      title: ['What it’s worth.', 'Where you buy it.'],
      markets: {
        kicker: 'Four markets',
        title: 'Every market on one card.',
        body: 'TCGplayer, eBay, PSA 10 and Cardmarket in euros. In your currency.',
      },
      card: {
        name: 'Mew ex',
        number: '205/165',
        set: 'Scarlet & Violet 151',
        track: 'Track price',
        rarity: 'Special Illustration Rare · Holo',
        manage: 'Manage copies',
        yours: ['Your collection', '1 copy'] as [string, string],
        boxes: [
          ['TCGplayer', '$32.40', 'Market price'],
          ['eBay', '$33.70', 'Sold yesterday'],
          ['PSA 10', '$118', 'Sold 12 Sep'],
          ['Cardmarket', '€27.86', 'Price trend'],
        ] as (readonly [string, string, string])[],
      },
      alerts: {
        kicker: 'Price alerts',
        title: 'Know when a price moves.',
        body: 'A push the moment a card hits your target.',
        push: ['Price alert: Charizard ex', 'Now $412 — above your $400 target.', 'now'],
        tracker: ['Charizard ex', 'Market value', '$412', 'Tracking', 'Target reached'],
      },
      hide: {
        kicker: 'Your cards first',
        title: 'Or hide every price.',
        body: 'One switch. Just your collection.',
        toggle: 'Show values',
        rows: [
          ['Charizard ex', '151 · 199/165', '$352', 'charizard'],
          ['Umbreon VMAX', 'Evolving Skies · 215/203', '$1,024', 'umbreon'],
          ['Pikachu', '151 · 173/165', '$76', 'pikachu'],
        ],
      },
    },
    catalogue: {
      eyebrow: 'The catalogue',
      title: ['Every card.', 'Every set.'],
      body: '20,000+ English cards from 1999’s Base Set to the newest release, every Japanese set, and the special printings in between.',
      sets: ['English', 'Japanese', 'sets'],
    },
    more: {
      eyebrow: 'Everything else',
      title: ['Small things.', 'Done properly.'],
      lang: [
        'Your language',
        'German card names wherever they exist. The app speaks English and German.',
      ],
      langDemo: ['Charizard ex', 'Glurak-ex'],
      jp: ['Japanese cards', 'Every Japanese set as its own catalogue, with its own prices.'],
      jpDemo: ['リザードンex', 'Charizard ex · 151', 'JP'],
      import: ['Bring your collection', 'From another app or a spreadsheet, checked card by card.'],
      importDemo: ['CSV', '248 cards'],
      offline: [
        'Works offline',
        'At a card show with no signal, MonDex keeps scanning and syncs later.',
      ],
      offlineDemo: ['Airplane mode', 'Charizard ex', 'Saved · syncs later'],
      widget: ['Widgets', 'Your collection and your next Pokédex goal on the Home Screen.'],
      widgetDemo: ['Kanto Living Dex', '142 / 151', 'cards'],
      goals: [
        'Goals & lists',
        'Wishlist, trade and grade lists, and goals like a Kanto Living Dex.',
      ],
      goalsDemo: [
        ['Kanto Living Dex', '142 / 151', '0.94'],
        ['Every Charizard', '18 / 25', '0.72'],
        ['Fire type', 'Done', '1'],
      ],
    },
    plus: {
      eyebrow: 'Pricing',
      title: ['Free to collect.', 'Plus to go faster.'],
      billing: ['Monthly', 'Yearly'],
      save: 'Save 37%',
      free: {
        name: 'Free',
        price: '$0',
        per: 'forever',
        items: [
          'Pokédex, sets, lists and goals',
          'Add cards by search',
          'Prices and 3 price alerts',
          '6 months of price history',
          'Export your collection anytime',
        ],
      },
      paid: {
        name: 'MonDex Plus',
        month: '$3.99',
        perMonth: '/ month',
        year: '$29.99',
        perYear: '/ year',
        yearNote: '$2.50 a month, billed yearly',
        items: [
          'Unlimited scanning: Auto & Batch, also offline',
          '20 price alerts',
          '2 years of price history',
          'Insights into your collection’s value',
          'Every automation and accent colour',
        ],
      },
      week: 'Your first scan starts a free Welcome Week of Plus.',
      weekNote: 'No payment details. Nothing renews by itself.',
      invite: 'Invite a friend: once they’re collecting, you both get 7 more days.',
      days: ['Day 1', 'Day 7'],
    },
    faq: {
      title: 'Questions',
      items: [
        [
          'Which phones does MonDex run on?',
          'MonDex is coming to iPhone first. Android follows soon.',
          'MonDex is on the App Store for iPhone. Android follows soon.',
        ],
        [
          'Which cards does it know?',
          'Every English set from the 1999 Base Set to the newest release, special printings like Poké Ball and Master Ball patterns, and every Japanese set.',
        ],
        [
          'Which languages does it speak?',
          'The app is in English and German, and card names appear in German wherever a German name exists. A card printed in another language is recognised by its artwork and saved with your copy’s language.',
        ],
        [
          'Where do the prices come from?',
          'TCGplayer market prices, Cardmarket in euros for English cards, and eBay sales, updated daily and shown in your currency.',
        ],
        [
          'Can I scan without a connection?',
          'Yes. MonDex downloads an offline pack while you’re online, recognises cards without a connection and syncs them when you’re back.',
        ],
        [
          'Can I bring my existing collection?',
          'Yes. Import an export from another app, a MonDex backup or any spreadsheet. You see every card first, and nothing is guessed.',
        ],
        [
          'What does it cost?',
          'Collecting is free: your Pokédex, sets, lists, prices and exports. Scanning after your free Welcome Week, more price alerts and deeper insights are MonDex Plus, $3.99 a month or $29.99 a year.',
        ],
      ] as (readonly string[])[],
    },
    final: {
      title: ['Your next discovery.', 'Starts here.'],
      body: 'Be the first to know when MonDex is on the App Store.',
      bodyLive: 'Free to download, with a free week of MonDex Plus.',
    },
    waitlist: {
      email: 'Email address',
      action: 'Notify me',
      sending: 'Joining…',
      proof: '{n}+ collectors are waiting.',
      success: 'You’re on the list.',
      successBody: 'We’ll email you once, when MonDex is ready.',
      emailError: 'Please enter a valid email address.',
      rateError: 'Too many attempts. Please try again in a few minutes.',
      serverError: 'That didn’t work. Please try again.',
      consent: 'One email when MonDex launches. Withdraw anytime.',
      privacy: 'Privacy',
      platforms: 'iPhone first · Android soon',
    },
    store: { badge: 'Download on the App Store', note: 'Free · iPhone' },
    footer: {
      tagline: 'Your Pokémon collection. Complete.',
      contact: 'Contact',
      privacy: 'Privacy',
      terms: 'Terms of use',
      imprint: 'Legal notice',
      note: 'Screens show MonDex on iPhone. Prices and progress on this page are examples.',
      legal:
        'Pokémon and Pokémon card names and images are trademarks of their respective owners. MonDex is an independent app and is not affiliated with Nintendo, Creatures, GAME FREAK or The Pokémon Company.',
    },
  },
  de: {
    meta: {
      title: 'MonDex: Pokémon Karten Scanner, Wert & Pokédex-App',
      description:
        'Pokémon-Karten scannen und den Wert sofort sehen: Cardmarket-Preise in Euro, TCGplayer und eBay, deutsche Kartennamen, japanische Karten und ein Pokédex zum Abhaken.',
    },
    skip: 'Zum Inhalt',
    nav: {
      scan: 'Scanner',
      dex: 'Pokédex',
      prices: 'Preise',
      plus: 'Plus',
      faq: 'Fragen',
      cta: 'MonDex holen',
      ctaLive: 'Laden',
    },
    hero: {
      badge: 'Pokémon-Karten-Scanner fürs iPhone',
      title: ['Scanne deine Karten.', 'Vervollständige deinen', 'Pokédex.'],
      body: 'Halte eine Karte vors Handy. MonDex weiß sofort, welche es ist, was sie wert ist und welches Pokémon sie in deinen Dex bringt.',
      chips: [
        ['Glurak-ex', 'Hinzugefügt · 325 €'],
        ['Neu in deinem Pokédex', '#006 Glurak'],
        ['Kanto-Living-Dex', '142 / 151'],
      ],
    },
    home: {
      title: 'Start',
      collection: 'Deine Sammlung',
      cards: 'Karten',
      pokedex: 'Pokédex',
      edit: 'Startseite bearbeiten',
      continueLabel: 'Weitersammeln',
      path: 'Kanto-Living-Dex',
      togo: 'Noch 142 Pokémon',
      viewDex: 'Zum Dex',
      recent: 'Zuletzt hinzugefügt',
      tabs: ['Start', 'Dex', 'Scannen', 'Karten', 'Wert'],
    },
    statement: 'Jede Karte {card:umbreon} hat eine Geschichte. MonDex {orbit} bewahrt sie.',
    scan: {
      eyebrow: 'Scannen',
      title: ['Handy draufhalten.', 'Fertig.'],
      points: [
        ['Auto', 'Karte für Karte. Nichts drücken.'],
        ['Stapel', 'Bis zu 100 Karten, vor dem Speichern geprüft.'],
        ['Offline', 'Englisch und Japanisch, auch ohne Empfang.'],
      ],
      chips: ['Freihändig', 'Englisch & Japanisch', 'Auch offline'],
      speed: ['0,3', 'Sofort erkannt.', 'Typische Zeit von der Karte im Bild bis zum Treffer.'],
      screen: {
        modes: ['Auto', 'Stapel'],
        cards: [
          ['Glurak-ex', '151 · 199/165', '325 €'],
          ['Mew-ex', '151 · 205/165', '28 €'],
          ['Pikachu', '151 · 173/165', '70 €'],
        ],
        total: ['Auto', '1 Karte · 325 €', '2 Karten · 353 €', '3 Karten · 423 €'],
      },
    },
    dex: {
      eyebrow: 'Dein Pokédex',
      title: ['Jedes Pokémon, das du hast.', 'Jedes, das noch fehlt.'],
      body: 'Alle 1.025 Pokémon, gefüllt, während du sammelst. Jedes neue leuchtet an seinem Platz auf, und die nächste Lücke wartet schon.',
      counter: 'von 1.025 entdeckt',
      fresh: 'Neu in deinem Pokédex',
      names: {
        1: 'Bisasam',
        4: 'Glumanda',
        7: 'Schiggy',
        25: 'Pikachu',
        54: 'Enton',
        94: 'Gengar',
        129: 'Karpador',
        133: 'Evoli',
        143: 'Relaxo',
        149: 'Dragoran',
        150: 'Mewtu',
        151: 'Mew',
        155: 'Feurigel',
        175: 'Togepi',
        197: 'Nachtara',
        249: 'Lugia',
        257: 'Lohgock',
        282: 'Guardevoir',
      } as Record<number, string>,
      undiscovered: 'Unentdeckt',
    },
    prices: {
      eyebrow: 'Preise',
      title: ['Was sie wert ist.', 'Da, wo du kaufst.'],
      markets: {
        kicker: 'Vier Märkte',
        title: 'Jeder Markt auf einer Karte.',
        body: 'Cardmarket in Euro, TCGplayer, eBay und PSA 10. In deiner Währung.',
      },
      card: {
        name: 'Mew-ex',
        number: '205/165',
        set: 'Scarlet & Violet 151',
        track: 'Preis verfolgen',
        rarity: 'Special Illustration Rare · Holo',
        manage: 'Exemplare verwalten',
        yours: ['Deine Sammlung', '1 Exemplar'] as [string, string],
        boxes: [
          ['TCGplayer', '30,13 €', 'Marktpreis'],
          ['eBay', '31,34 €', 'Gestern verkauft'],
          ['PSA 10', '109 €', 'Verkauft am 12. Sep.'],
          ['Cardmarket', '27,86 €', 'Preistrend'],
        ] as (readonly [string, string, string])[],
      },
      alerts: {
        kicker: 'Preisalarme',
        title: 'Wisse, wann sich ein Preis bewegt.',
        body: 'Eine Mitteilung, sobald eine Karte dein Ziel erreicht.',
        push: ['Preisalarm: Glurak-ex', 'Jetzt 382 € – über deinem Ziel von 370 €.', 'jetzt'],
        tracker: ['Glurak-ex', 'Marktwert', '382 €', 'Wird verfolgt', 'Ziel erreicht'],
      },
      hide: {
        kicker: 'Deine Karten zuerst',
        title: 'Oder blende alle Preise aus.',
        body: 'Ein Schalter. Nur deine Sammlung.',
        toggle: 'Werte zeigen',
        rows: [
          ['Glurak-ex', '151 · 199/165', '325 €', 'charizard'],
          ['Nachtara-VMAX', 'Drachenwandel · 215/203', '945 €', 'umbreon'],
          ['Pikachu', '151 · 173/165', '70 €', 'pikachu'],
        ],
      },
    },
    catalogue: {
      eyebrow: 'Der Katalog',
      title: ['Jede Karte.', 'Jedes Set.'],
      body: 'Über 20.000 englische Karten vom Grundset 1999 bis zur neuesten Erweiterung, jedes japanische Set und die Sonderdrucke dazwischen.',
      sets: ['Englisch', 'Japanisch', 'Sets'],
    },
    more: {
      eyebrow: 'Und sonst',
      title: ['Kleine Dinge.', 'Richtig gemacht.'],
      lang: [
        'Deine Sprache',
        'Deutsche Kartennamen, wo es sie gibt. Die App spricht Deutsch und Englisch.',
      ],
      langDemo: ['Charizard ex', 'Glurak-ex'],
      jp: ['Japanische Karten', 'Jedes japanische Set als eigener Katalog, mit eigenen Preisen.'],
      jpDemo: ['リザードンex', 'Charizard ex · 151', 'JP'],
      import: [
        'Bring deine Sammlung mit',
        'Aus einer anderen App oder einer Tabelle, Karte für Karte geprüft.',
      ],
      importDemo: ['CSV', '248 Karten'],
      offline: [
        'Auch offline',
        'Auf der Tauschbörse ohne Empfang scannt MonDex weiter und gleicht später ab.',
      ],
      offlineDemo: ['Flugmodus', 'Glurak-ex', 'Gespeichert · wird abgeglichen'],
      widget: ['Widgets', 'Deine Sammlung und dein nächstes Pokédex-Ziel auf dem Home-Bildschirm.'],
      widgetDemo: ['Kanto-Living-Dex', '142 / 151', 'Karten'],
      goals: [
        'Ziele & Listen',
        'Wunschliste, Tausch- und Grading-Listen und Ziele wie ein Kanto-Living-Dex.',
      ],
      goalsDemo: [
        ['Kanto-Living-Dex', '142 / 151', '0.94'],
        ['Jedes Glurak', '18 / 25', '0.72'],
        ['Typ Feuer', 'Geschafft', '1'],
      ],
    },
    plus: {
      eyebrow: 'Preise',
      title: ['Sammeln ist kostenlos.', 'Plus macht dich schneller.'],
      billing: ['Monatlich', 'Jährlich'],
      save: 'Spare 37 %',
      free: {
        name: 'Kostenlos',
        price: '0 €',
        per: 'für immer',
        items: [
          'Pokédex, Sets, Listen und Ziele',
          'Karten per Suche hinzufügen',
          'Preise und 3 Preisalarme',
          '6 Monate Preisverlauf',
          'Sammlung jederzeit exportieren',
        ],
      },
      paid: {
        name: 'MonDex Plus',
        month: '3,99 €',
        perMonth: '/ Monat',
        year: '29,99 €',
        perYear: '/ Jahr',
        yearNote: '2,50 € im Monat, jährlich abgerechnet',
        items: [
          'Unbegrenzt scannen: Auto & Stapel, auch offline',
          '20 Preisalarme',
          '2 Jahre Preisverlauf',
          'Einblicke in den Wert deiner Sammlung',
          'Alle Automationen und Akzentfarben',
        ],
      },
      week: 'Dein erster Scan startet eine kostenlose Willkommenswoche mit Plus.',
      weekNote: 'Keine Zahlungsdaten. Nichts verlängert sich von selbst.',
      invite: 'Lade Freunde ein: Sobald sie sammeln, bekommt ihr beide 7 Tage dazu.',
      days: ['Tag 1', 'Tag 7'],
    },
    faq: {
      title: 'Fragen',
      items: [
        [
          'Auf welchen Handys läuft MonDex?',
          'MonDex kommt zuerst aufs iPhone. Android folgt bald.',
          'MonDex gibt es im App Store fürs iPhone. Android folgt bald.',
        ],
        [
          'Welche Karten kennt MonDex?',
          'Jedes englische Set vom Grundset 1999 bis zur neuesten Erweiterung, Sonderdrucke wie Poké-Ball- und Master-Ball-Muster und jedes japanische Set.',
        ],
        [
          'Welche Sprachen spricht MonDex?',
          'Die App gibt es auf Deutsch und Englisch, und Kartennamen erscheinen auf Deutsch, wo es einen deutschen Namen gibt. Eine Karte in einer anderen Sprache wird am Artwork erkannt und mit der Sprache deines Exemplars gespeichert.',
        ],
        [
          'Woher kommen die Preise?',
          'Cardmarket in Euro für englische Karten, TCGplayer-Marktpreise und eBay-Verkäufe, täglich aktualisiert und in deiner Währung.',
        ],
        [
          'Kann ich ohne Verbindung scannen?',
          'Ja. MonDex lädt ein Offline-Paket, solange du online bist, erkennt Karten ohne Verbindung und gleicht sie ab, sobald du wieder online bist.',
        ],
        [
          'Kann ich meine Sammlung mitnehmen?',
          'Ja. Importiere einen Export aus einer anderen App, ein MonDex-Backup oder eine beliebige Tabelle. Du siehst jede Karte vorher, und nichts wird geraten.',
        ],
        [
          'Was kostet MonDex?',
          'Sammeln ist kostenlos: Pokédex, Sets, Listen, Preise und Exporte. Scannen nach der kostenlosen Willkommenswoche, mehr Preisalarme und tiefere Einblicke gehören zu MonDex Plus, 3,99 € im Monat oder 29,99 € im Jahr.',
        ],
      ] as (readonly string[])[],
    },
    final: {
      title: ['Deine nächste Entdeckung.', 'Beginnt hier.'],
      body: 'Erfahre als Erstes, wenn MonDex im App Store ist.',
      bodyLive: 'Kostenlos laden, mit einer Gratis-Woche MonDex Plus.',
    },
    waitlist: {
      email: 'E-Mail-Adresse',
      action: 'Vormerken',
      sending: 'Wird eingetragen…',
      proof: 'Schon {n}+ Sammler warten.',
      success: 'Du stehst auf der Liste.',
      successBody: 'Wir schreiben dir einmal, sobald MonDex bereit ist.',
      emailError: 'Bitte gib eine gültige E-Mail-Adresse ein.',
      rateError: 'Zu viele Versuche. Bitte versuche es in ein paar Minuten erneut.',
      serverError: 'Das hat nicht geklappt. Bitte versuche es erneut.',
      consent: 'Eine E-Mail zum Start von MonDex. Jederzeit widerrufbar.',
      privacy: 'Datenschutz',
      platforms: 'Zuerst iPhone · Android bald',
    },
    store: { badge: 'Laden im App Store', note: 'Kostenlos · iPhone' },
    footer: {
      tagline: 'Deine Pokémon-Sammlung. Komplett.',
      contact: 'Kontakt',
      privacy: 'Datenschutz',
      terms: 'Nutzungsbedingungen',
      imprint: 'Impressum',
      note: 'Die Bildschirme zeigen MonDex auf dem iPhone. Preise und Fortschritte auf dieser Seite sind Beispiele.',
      legal:
        'Pokémon sowie Namen und Bilder von Pokémon-Karten sind Marken ihrer jeweiligen Inhaber. MonDex ist eine unabhängige App und steht in keiner Verbindung zu Nintendo, Creatures, GAME FREAK oder The Pokémon Company.',
    },
  },
};

export type HomeCopy = (typeof homeCopy)['en'];
